### ISSUE TITLE
Jul/2/2020 Review

### ISSUE THREAD

**Issue by eliasecasta** [mikethreels/web_scraper_ruby#2]
Hello Michael, your project looks really nice! One thing that I saw that you can improve:

- Use overloaded methods for your ans.one/two/three etc methods, with this option you will just create one method that accepts different amounts of arguments, it is really nice!

https://www.geeksforgeeks.org/method-overloading-in-ruby/#:~:text=Method%20overloading%20is%20a%20feature,can%20have%20different%20return%20type.

**Comment by mikethreels** [comment]
Hi Elias,

thank you for the tip and the article it was very helpful.
